model_list:
  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: openrouter/alibaba/qwen3-coder-plus
      api_base: os.environ/OPENAI_API_BASE
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: openrouter/alibaba/qwen3-coder-plus
      api_base: os.environ/OPENAI_API_BASE
      api_key: os.environ/OPENAI_API_KEY
general_settings:
  master_key: sk-test-123